"""Scenario fixtures for the static routing conformance suite.

Each fixture declares the request, the authority, and the expected routing
decision. `scripts/routing_rules.validate_scenario` checks that each expect
block is internally consistent with the cross-field invariants from SKILL.md.
"""

from __future__ import annotations

SCENARIOS = [
    {
        "id": "001-small-sequential-task",
        "request": "Rename the local variable in this one function.",
        "authority": "implicit",
        "expect": {
            "topology": "single",
            "wakeup": "none",
            "convergence": "single-pass",
            "independent_review_gate": "not-required",
            "independent_review_status": "not-applicable",
            "human_gates": ["none"],
        },
        "rationale": "One bounded outcome, low-risk mutation boundary, directly verifiable.",
    },
    {
        "id": "002-two-independent-outcomes",
        "request": "Add import validation to the auth migration and verify it.",
        "authority": "implicit",
        "expect": {
            "topology": "temporary",
            "wakeup": "none",
            "convergence": "phase-gated",
            "independent_review_gate": "required",
            "review_trigger": "data-migration-overwrite-loss",
            "review_stop_condition": "one full review plus one focused recheck",
            "human_gates": ["none"],
        },
        "rationale": "Two independent outcomes; migration record parsing is a data-integrity boundary.",
    },
    {
        "id": "003-persistent-explicit-authority",
        "request": "Use $agent-team with a persistent team to operate monthly release prep.",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "persistent",
            "wakeup": "heartbeat",
            "wakeup_stop_condition": "release shipped or retirement trigger reached",
            "convergence": "phase-gated",
            "independent_review_gate": "required",
            "review_trigger": "deployment-publication-payment-deletion-account-permissions",
            "review_stop_condition": "release gate review completes",
            "human_gates": ["deployment", "publication"],
            "persistence_authority": True,
            "persistence_future_reuse": True,
            "persistence_stable_responsibilities": True,
            "persistence_role_continuity": True,
            "persistence_direct_reentry_value": True,
            "persistence_lifecycle": True,
            "lifecycle_team_name": "[Team:release]",
            "lifecycle_controller": "release controller task",
            "lifecycle_write_scopes": "release checklist, dependency audit notes",
            "lifecycle_checkpoint": "after each release candidate",
            "lifecycle_completion": "release shipped",
            "lifecycle_retirement_trigger": "no future releases planned",
        },
        "rationale": "All six persistence gates pass with explicit invocation and full lifecycle.",
    },
    {
        "id": "004-persistent-missing-gates",
        "request": "Use $agent-team with a persistent team to keep monitoring this project.",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "temporary",
            "wakeup": "heartbeat",
            "wakeup_stop_condition": "monitoring ends or blocks on user input",
            "convergence": "single-pass",
            "independent_review_gate": "not-required",
            "independent_review_status": "not-applicable",
            "human_gates": ["none"],
        },
        "rationale": "The persistent request lacks complete reuse and lifecycle evidence, so downgrade to temporary while retaining recurring follow-up.",
    },
    {
        "id": "005-evidence-loop-requires-review",
        "request": "Use $agent-team to keep retrying the flaky test until it passes.",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "single",
            "wakeup": "none",
            "convergence": "evidence-loop",
            "independent_review_gate": "required",
            "review_trigger": "high-impact-insufficient-checks",
            "review_stop_condition": "evidence-loop review completes",
            "human_gates": ["none"],
        },
        "rationale": "Evidence loop always requires independent review; frozen acceptance in a linked worktree.",
    },
    {
        "id": "006-security-trust-boundary",
        "request": "Migrate the auth service to a new token format and make sure nothing breaks.",
        "authority": "implicit",
        "expect": {
            "topology": "temporary",
            "wakeup": "none",
            "convergence": "evidence-loop",
            "independent_review_gate": "required",
            "review_trigger": "security-authorization-trust-boundary",
            "review_stop_condition": "security review plus focused recheck",
            "human_gates": ["deployment"],
        },
        "rationale": "Trust boundary survives deterministic checks; deployment stays behind its gate.",
    },
    {
        "id": "007-cross-system-contract",
        "request": "Sync the order API with the warehouse service and verify the contract.",
        "authority": "implicit",
        "expect": {
            "topology": "temporary",
            "wakeup": "none",
            "convergence": "phase-gated",
            "independent_review_gate": "required",
            "review_trigger": "api-sync-persistence-contract",
            "review_stop_condition": "contract review plus focused recheck",
            "human_gates": ["none"],
        },
        "rationale": "Cross-system contract is a named residual risk after deterministic checks.",
    },
    {
        "id": "008-content-analysis-readonly",
        "request": "Use $agent-team to analyze this research paper and summarize the gaps.",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "single",
            "wakeup": "none",
            "convergence": "single-pass",
            "independent_review_gate": "not-required",
            "independent_review_status": "not-applicable",
            "human_gates": ["none"],
        },
        "rationale": "Read-only analysis; default review backend native-verifier only when gate is required.",
    },
    {
        "id": "009-vault-write-explicit",
        "request": "Use $agent-team to reorganize the Obsidian vault notes into a new structure.",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "temporary",
            "wakeup": "none",
            "convergence": "phase-gated",
            "independent_review_gate": "not-required",
            "independent_review_status": "not-applicable",
            "human_gates": ["none"],
        },
        "rationale": "Writable vault work only with explicit user ask and governance permission; no evidence loop on a vault.",
    },
    {
        "id": "010-no-invented-work",
        "request": "Use $agent-team to complete: write a blog post AND research competitors AND refactor the build.",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "single",
            "wakeup": "none",
            "convergence": "single-pass",
            "independent_review_gate": "not-required",
            "independent_review_status": "not-applicable",
            "human_gates": ["publication"],
        },
        "rationale": "Never invent work to involve every backend; objective is vague, so ask before delegating.",
    },
    {
        "id": "011-chinese-recurring-monitoring",
        "request": "使用 $agent-team 每天持续监控这个项目。",
        "authority": "explicit-invocation",
        "expect": {
            "topology": "temporary",
            "wakeup": "heartbeat",
            "wakeup_stop_condition": "用户输入、无进展或项目完成",
            "convergence": "single-pass",
            "independent_review_gate": "not-required",
            "independent_review_status": "not-applicable",
            "human_gates": ["none"],
        },
        "rationale": "Documented Chinese recurring wording requires an explicit bounded wakeup.",
    },
]
